ENT.Base	    			= "base_ai"
ENT.Type	    			= "ai"
ENT.PrintName				= "NPC Info"
ENT.Author					= "hodos"
ENT.Category				= "hodos"
ENT.Instructions			= "NPC interaction"
ENT.Contact					= "hodos#8161"
ENT.Spawnable				= true
ENT.AdminSpawnable			= true
ENT.AutomaticFrameAdvance	= true